services:
  - type: web
    name: tds-virtual-ta
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api3:app

    envVars:
      - key: OPENAI_API_KEY
        sync: false
